spring.application.name=agendamedica
# 1. URL base (Cortamos todo a partir del signo de interrogación '?')
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres

# 2. El usuario (Lo que estaba después de '?user=')
spring.datasource.username=postgres.btjhecdoosmqzqmdiicf

# 3. La contraseña que creaste al iniciar el proyecto
spring.datasource.password=mis5familiaresLocos

# 4. Configuraciones obligatorias de JPA y el Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURACIÓN DE SEGURIDAD JWT
# ==========================================
# Clave secreta (mínimo 32 caracteres para HMAC-SHA256)
jwt.secret=EstaEsUnaClaveSuperSecretaParaLaAgendaMedica2026!
# Expiración en milisegundos (86400000 ms = 24 horas)
jwt.expiration=86400000
server.port=8081